# load base python image
FROM appsvc/python
EXPOSE 5000

LABEL Name=music-recommendation-service Version=0.0.1


RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app/

#pyodbc
RUN apt-get update \
        && apt-get install -y --no-install-recommends curl build-essential gcc unixodbc-dev

# Add SQL Server ODBC Driver 17 for Ubuntu 18.04
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc


RUN pip install -r requirements.txt
ADD . /app/

# ssh
ENV SSH_PASSWD "root:Docker!"

ENV PREDICTIONS_PATH="https://recommendationdata.blob.core.windows.net/predictions/"
ENV SQL_SERVER="20.212.196.50"
ENV MUSICPLAYER_DB="MUSICPLAYER"
ENV SQL_USERNAME="sa"
ENV SQL_PASSWORD="29327Cab@456789"
ENV PORT=5000

RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
        && apt-get install -y --no-install-recommends openssh-server \
        && echo "$SSH_PASSWD" | chpasswd 

COPY sshd_config /etc/ssh/
COPY init.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/init.sh
EXPOSE 8000 2222

ENTRYPOINT ["init.sh"]